apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: models-app-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/torpedobr/argo-cd.git
        revision: main
        directories:
          - path: "models/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: argopoc-project
      source:
        repoURL: https://github.com/torpedobr/argo-cd.git
        targetRevision: app-set
        chart: '{{path.basename}}'
        helm:
          valueFiles:
            - dev/{{path.basename}}.yaml
      destination:
        server: https://c111-e.us-east.containers.cloud.ibm.com:31252
        namespace: argo-poc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true