apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: models-app-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/torpedobr/argo-cd.git
        revision: app-set
        directories:
          - path: "models/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: argopoc-project
      source:
        repoURL: git@github.ibm.com:dmkonovalov/argotest.git
        targetRevision: app-set
        chart: '{{path.basename}}'
        helm:
          valueFiles:
            - dev/{{path.basename}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argo-poc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true