apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argopoc-project
  namespace: argocd
spec:
  description: "This is an example ArgoCD project"
  sourceRepos:
    - https://github.ibm.com/dmkonovalov/argotest.git   # Allowed source repositories
  destinations:
    - namespace: argocd                       # Allowed namespace for applications
      server: https://127.0.0.1:6443   # Allowed cluster URL